org.gradle.jvmargs=-Xmx1G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

systemProp.http.proxyHost=172.19.0.1
systemProp.http.proxyPort=10809
systemProp.https.proxyHost=172.19.0.1
systemProp.https.proxyPort=10809

# Batasi jumlah worker paralel Gradle agar tidak terlalu membebani RAM
org.gradle.workers.max=2

# Gunakan Kotlin compiler in-process untuk mengurangi overhead memori
kotlin.compiler.execution.strategy=in-process

# Aktifkan daemon Gradle untuk mempercepat build (jika RAM cukup)
org.gradle.daemon=false

# Aktifkan konfigurasi paralel build (hati-hati jika RAM terbatas)
org.gradle.parallel=false
